version: "3.9"

services:
  catcollectorspa:
    image: postgres
    container_name: catcollectorspa
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: cat_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catcollectorspa

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_api
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev
    depends_on:
      - catcollectorspa

volumes:
  postgres_data:
