# Generated by Django 5.2 on 2025-05-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_vehicle_type_alter_vehicle_model_alter_vehicle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
