# Generated by Django 5.2 on 2025-05-05 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_vehicle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='garage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main_app.garage'),
        ),
    ]
